[tool.poetry]
name = "python-web"
version = "0.1.0"
description = ""
authors = ["retOK1986 <retOK@i.ua>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
psycopg2 = "^2.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
