"""Init

Revision ID: 58a041930aad
Revises: 
Create Date: 2024-02-23 00:50:50.569431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a041930aad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('grades', sa.Column('date_received', sa.Date(), nullable=True))
    op.alter_column('grades', 'grade',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('grades_subject_id_fkey', 'grades', type_='foreignkey')
    op.drop_constraint('grades_student_id_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'grades', 'subjects', ['subject_id'], ['id'])
    op.drop_column('grades', 'grade_date')
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('students', 'fullname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_constraint('students_group_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'])
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=175),
               nullable=True)
    op.drop_constraint('subjects_teacher_id_fkey', 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'])
    op.alter_column('teachers', 'fullname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'fullname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key('subjects_teacher_id_fkey', 'subjects', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=175),
               nullable=False)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_group_id_fkey', 'students', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('students', 'fullname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('grades', sa.Column('grade_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_student_id_fkey', 'grades', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('grades_subject_id_fkey', 'grades', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('grades', 'grade',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('grades', 'date_received')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('age', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.CheckConstraint('age > 18 AND age < 75', name='users_age_check'),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
