[tool.poetry]
name = "dz-9"
version = "0.1.0"
description = ""
authors = ["retOK1986 <retOK@i.ua>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.11.1"
mongoengine = "^0.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
